const APP_THEME_MODE = 'APP_THEME_MODE';
const APP_BG_COLOR = 'APP_BG_COLOR';
const APP_BG_COLOR_LABEL = 'APP_BG_COLOR_LABEL';
const APP_BG_COLOR_OPACITY = 'APP_BG_COLOR_OPACITY';
const APP_COLORS_HISTORY = 'APP_COLORS_HISTORY';
const FIRST_TIME_IN_APP = 'FIRST_TIME_IN_APP';
